// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: masterworker.proto

#include "masterworker.pb.h"
#include "masterworker.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace masterworker {

static const char* WorkerReq_method_names[] = {
  "/masterworker.WorkerReq/performtask",
};

std::unique_ptr< WorkerReq::Stub> WorkerReq::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WorkerReq::Stub> stub(new WorkerReq::Stub(channel));
  return stub;
}

WorkerReq::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_performtask_(WorkerReq_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WorkerReq::Stub::performtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails& request, ::masterworker::WorkConfirmation* response) {
  return ::grpc::internal::BlockingUnaryCall< ::masterworker::WorkDetails, ::masterworker::WorkConfirmation, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_performtask_, context, request, response);
}

void WorkerReq::Stub::experimental_async::performtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails* request, ::masterworker::WorkConfirmation* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::masterworker::WorkDetails, ::masterworker::WorkConfirmation, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_performtask_, context, request, response, std::move(f));
}

void WorkerReq::Stub::experimental_async::performtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails* request, ::masterworker::WorkConfirmation* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_performtask_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::masterworker::WorkConfirmation>* WorkerReq::Stub::PrepareAsyncperformtaskRaw(::grpc::ClientContext* context, const ::masterworker::WorkDetails& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::masterworker::WorkConfirmation, ::masterworker::WorkDetails, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_performtask_, context, request);
}

::grpc::ClientAsyncResponseReader< ::masterworker::WorkConfirmation>* WorkerReq::Stub::AsyncperformtaskRaw(::grpc::ClientContext* context, const ::masterworker::WorkDetails& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncperformtaskRaw(context, request, cq);
  result->StartCall();
  return result;
}

WorkerReq::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerReq_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerReq::Service, ::masterworker::WorkDetails, ::masterworker::WorkConfirmation, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerReq::Service* service,
             ::grpc::ServerContext* ctx,
             const ::masterworker::WorkDetails* req,
             ::masterworker::WorkConfirmation* resp) {
               return service->performtask(ctx, req, resp);
             }, this)));
}

WorkerReq::Service::~Service() {
}

::grpc::Status WorkerReq::Service::performtask(::grpc::ServerContext* context, const ::masterworker::WorkDetails* request, ::masterworker::WorkConfirmation* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace masterworker

