// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: masterworker.proto
#ifndef GRPC_masterworker_2eproto__INCLUDED
#define GRPC_masterworker_2eproto__INCLUDED

#include "masterworker.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace masterworker {

class WorkerReq final {
 public:
  static constexpr char const* service_full_name() {
    return "masterworker.WorkerReq";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status performtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails& request, ::masterworker::WorkConfirmation* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::WorkConfirmation>> Asyncperformtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::WorkConfirmation>>(AsyncperformtaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::WorkConfirmation>> PrepareAsyncperformtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::WorkConfirmation>>(PrepareAsyncperformtaskRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void performtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails* request, ::masterworker::WorkConfirmation* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void performtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails* request, ::masterworker::WorkConfirmation* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void performtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails* request, ::masterworker::WorkConfirmation* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::WorkConfirmation>* AsyncperformtaskRaw(::grpc::ClientContext* context, const ::masterworker::WorkDetails& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::WorkConfirmation>* PrepareAsyncperformtaskRaw(::grpc::ClientContext* context, const ::masterworker::WorkDetails& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status performtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails& request, ::masterworker::WorkConfirmation* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::WorkConfirmation>> Asyncperformtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::WorkConfirmation>>(AsyncperformtaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::WorkConfirmation>> PrepareAsyncperformtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::WorkConfirmation>>(PrepareAsyncperformtaskRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void performtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails* request, ::masterworker::WorkConfirmation* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void performtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails* request, ::masterworker::WorkConfirmation* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void performtask(::grpc::ClientContext* context, const ::masterworker::WorkDetails* request, ::masterworker::WorkConfirmation* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::masterworker::WorkConfirmation>* AsyncperformtaskRaw(::grpc::ClientContext* context, const ::masterworker::WorkDetails& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::masterworker::WorkConfirmation>* PrepareAsyncperformtaskRaw(::grpc::ClientContext* context, const ::masterworker::WorkDetails& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_performtask_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status performtask(::grpc::ServerContext* context, const ::masterworker::WorkDetails* request, ::masterworker::WorkConfirmation* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_performtask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_performtask() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_performtask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performtask(::grpc::ServerContext* /*context*/, const ::masterworker::WorkDetails* /*request*/, ::masterworker::WorkConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestperformtask(::grpc::ServerContext* context, ::masterworker::WorkDetails* request, ::grpc::ServerAsyncResponseWriter< ::masterworker::WorkConfirmation>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_performtask<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_performtask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_performtask() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::masterworker::WorkDetails, ::masterworker::WorkConfirmation>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::masterworker::WorkDetails* request, ::masterworker::WorkConfirmation* response) { return this->performtask(context, request, response); }));}
    void SetMessageAllocatorFor_performtask(
        ::grpc::experimental::MessageAllocator< ::masterworker::WorkDetails, ::masterworker::WorkConfirmation>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::masterworker::WorkDetails, ::masterworker::WorkConfirmation>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_performtask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performtask(::grpc::ServerContext* /*context*/, const ::masterworker::WorkDetails* /*request*/, ::masterworker::WorkConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* performtask(
      ::grpc::CallbackServerContext* /*context*/, const ::masterworker::WorkDetails* /*request*/, ::masterworker::WorkConfirmation* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* performtask(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::masterworker::WorkDetails* /*request*/, ::masterworker::WorkConfirmation* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_performtask<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_performtask<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_performtask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_performtask() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_performtask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performtask(::grpc::ServerContext* /*context*/, const ::masterworker::WorkDetails* /*request*/, ::masterworker::WorkConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_performtask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_performtask() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_performtask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performtask(::grpc::ServerContext* /*context*/, const ::masterworker::WorkDetails* /*request*/, ::masterworker::WorkConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestperformtask(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_performtask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_performtask() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->performtask(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_performtask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status performtask(::grpc::ServerContext* /*context*/, const ::masterworker::WorkDetails* /*request*/, ::masterworker::WorkConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* performtask(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* performtask(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_performtask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_performtask() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::masterworker::WorkDetails, ::masterworker::WorkConfirmation>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::masterworker::WorkDetails, ::masterworker::WorkConfirmation>* streamer) {
                       return this->Streamedperformtask(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_performtask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status performtask(::grpc::ServerContext* /*context*/, const ::masterworker::WorkDetails* /*request*/, ::masterworker::WorkConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedperformtask(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::masterworker::WorkDetails,::masterworker::WorkConfirmation>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_performtask<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_performtask<Service > StreamedService;
};

}  // namespace masterworker


#endif  // GRPC_masterworker_2eproto__INCLUDED
